Outgoing
team-pandora/transfers-gateway pull request #2
Opened 2022-08-04 10:09 UTC by yarinBenisty

2022-08-09 13:18 UTC, MichaelSimkin requested changes

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +        .get(`/${filters.from}/outgoing`, { params: filters })
make userId function parameter, (changes in controller as well)
```suggestion
        .get(`/${userId}/outgoing`, { params: { ...filters, from: userId } })
```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/outgoing/controller.ts
> +    res.json(await OutgoingManager.getOutgoingFileById(req.params.userId, req.params.fileId));
we get user from req.user.id not from params in all routes
```suggestion
    res.json(await OutgoingManager.getOutgoingFileById(req.user.id, req.params.fileId));
```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/outgoing/router.ts
> +    '/:userId/outgoing',
remove :userId in all routes
```suggestion
    '/outgoing',
```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/outgoing/validator.schema.ts
> +        userId: Joi.string().required(),
remove in all validators userId
```suggestion

```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/router.ts
> +appRouter.use('/api/users', userRouter);
remove /users
```suggestion
appRouter.use('/api', outgoingRouter);
appRouter.use('/api', userRouter);
```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/user/controller.ts
> +    res.json(await UserManager.checkPhonebookUsers(req.body.users));
```suggestion
    res.json(await UserManager.checkPhonebookUsers(req.query.query, req.query.limit));
```

2022-08-09 13:18 UTC, MichaelSimkin commented on src/express/user/controller.ts
> +    res.json(await UserManager.checkKartoffelUsers(req.query.source, req.query));
```suggestion
    res.json(await UserManager.checkKartoffelUsers(req.query.query, req.query.source));
```

2022-08-09 13:18 UTC, MichaelSimkin commented
Change folder `user` to `users`

2022-08-09 13:21 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +        .get(`/${filters.from}/outgoing`, { params: filters })
done

2022-08-09 13:22 UTC, yarinBenisty commented on src/express/outgoing/controller.ts
> +    res.json(await OutgoingManager.getOutgoingFileById(req.params.userId, req.params.fileId));
done

2022-08-09 13:22 UTC, yarinBenisty commented on src/express/outgoing/router.ts
> +    '/:userId/outgoing',
done

2022-08-09 13:25 UTC, yarinBenisty commented on src/express/outgoing/validator.schema.ts
> +        userId: Joi.string().required(),
done

2022-08-09 13:25 UTC, yarinBenisty commented on src/express/router.ts
> +appRouter.use('/api/users', userRouter);
done

2022-08-09 13:27 UTC, yarinBenisty commented on src/express/user/controller.ts
> +    res.json(await UserManager.checkKartoffelUsers(req.query.source, req.query));
done

2022-08-09 13:29 UTC, yarinBenisty commented
folder name changed :D

2022-08-09 13:32 UTC, yarinBenisty commented
dont forget to approve

2022-08-14 10:17 UTC, MichaelSimkin requested changes
Small changes needed

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileStatusById = async (fileId: mongoose.Types.ObjectId): Promise<IFileFlow> => {
Add userId verificatiion. Make axios request to get file where from=userId and check if exists.

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/router.ts
> +const appRouter: Router = Router();
Type not needed. (infered from Router();)
```suggestion
const appRouter = Router();
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/utils/joi.ts
> +    .custom((value) => new mongoose.Types.ObjectId(value));
We should work with strings in gateway

```suggestion
export const JoiMongoObjectId = Joi.string().hex().length(24);
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileById = async (userId: string, fileId: mongoose.Types.ObjectId): Promise<IOutgoingFile> => {
```suggestion
export const getOutgoingFileById = async (userId: string, fileId: string): Promise<IOutgoingFile> => {
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileStatusById = async (fileId: mongoose.Types.ObjectId): Promise<IFileFlow> => {
```suggestion
export const getOutgoingFileStatusById = async (userId: string, fileId: string): Promise<IFileFlow> => {
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +export const deleteOutgoingFile = async (userId: string, fileId: mongoose.Types.ObjectId): Promise<IOutgoingFile> => {
```suggestion
export const deleteOutgoingFile = async (userId: string, fileId: string): Promise<IOutgoingFile> => {
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/interface.ts
> +    _id: mongoose.Types.ObjectId;
```suggestion
    _id: string;
```

2022-08-14 10:17 UTC, MichaelSimkin commented on src/express/outgoing/interface.ts
> +    _id?: mongoose.Types.ObjectId;
```suggestion
    _id?: string;
```

2022-08-14 10:59 UTC, yarinBenisty commented on src/express/outgoing/controller.ts
> +    req: Request<{ userId: string; fileId: mongoose.Types.ObjectId }>,
done

2022-08-14 11:01 UTC, yarinBenisty commented on src/express/outgoing/controller.ts
> +    res.json(await OutgoingManager.getOutgoingFileStatusById(req.params.fileId));
done

2022-08-14 11:08 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileStatusById = async (fileId: mongoose.Types.ObjectId): Promise<IFileFlow> => {
done

2022-08-14 11:10 UTC, yarinBenisty commented on src/express/router.ts
> +const appRouter: Router = Router();
done

2022-08-14 11:11 UTC, yarinBenisty commented on src/utils/joi.ts
> +    .custom((value) => new mongoose.Types.ObjectId(value));
done

2022-08-14 11:12 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileById = async (userId: string, fileId: mongoose.Types.ObjectId): Promise<IOutgoingFile> => {
done

2022-08-14 11:13 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +export const getOutgoingFileStatusById = async (fileId: mongoose.Types.ObjectId): Promise<IFileFlow> => {
done

2022-08-14 11:13 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +export const deleteOutgoingFile = async (userId: string, fileId: mongoose.Types.ObjectId): Promise<IOutgoingFile> => {
done

2022-08-14 11:13 UTC, yarinBenisty commented on src/express/outgoing/interface.ts
> +    _id?: mongoose.Types.ObjectId;
done

2022-08-14 11:13 UTC, yarinBenisty commented on src/express/outgoing/interface.ts
> +    _id: mongoose.Types.ObjectId;
done

2022-08-21 08:45 UTC, sternomer approved these changes

2022-08-21 13:24 UTC, MichaelSimkin requested changes
Excellent, just two error message fixes.

2022-08-21 13:24 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +        throw new ServerError(StatusCodes.INTERNAL_SERVER_ERROR, 'Failed to get users.');
```suggestion
        throw new ServerError(StatusCodes.BAD_REQUEST, 'Failed to find users.');
```

2022-08-21 13:24 UTC, MichaelSimkin commented on src/express/outgoing/manager.ts
> +    if (file.from !== userId) throw new ServerError(StatusCodes.INTERNAL_SERVER_ERROR, 'User does not own file');
```suggestion
    if (file.from !== userId) throw new ServerError(StatusCodes.FORBIDDEN, 'User does not own file');
```

2022-08-21 13:33 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +        throw new ServerError(StatusCodes.INTERNAL_SERVER_ERROR, 'Failed to get users.');
done

2022-08-21 13:33 UTC, yarinBenisty commented on src/express/outgoing/manager.ts
> +    if (file.from !== userId) throw new ServerError(StatusCodes.INTERNAL_SERVER_ERROR, 'User does not own file');
done

2022-08-21 14:16 UTC, MichaelSimkin approved these changes

2022-08-21 14:16 UTC, merged